config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :don_vis

  resources :uploads, only: [:new, :create]
  root 'uploads#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/don_vi.rb
class DonVi < ApplicationRecord
    # Khai báo các trường
    self.table_name = "donvis"
  
    # Định nghĩa các trường
    # stt (integer)
    # ten (string)
    # cap (integer)
    # dia_chi (string)
    # dien_thoai (string)
    # ma_dinh_danh_dt (string)
    # code (string)
    # parent_code (string)
  
    # Thuộc tính liên quan
    # Quan hệ cha con với chính nó
    has_many :don_vi_con, class_name: "DonVi", primary_key: "code", foreign_key: "parent_code", dependent: :destroy
    belongs_to :don_vi_cha, class_name: "DonVi", primary_key: "code", foreign_key: "parent_code", optional: true
  
    # Validations
    # ...
    def has_children?
      self.don_vi_con.any?
    end
  
    def all_ancestors
      ancestors = []
      current_don_vi = self.don_vi_cha
  
      while current_don_vi.present?
        ancestors << current_don_vi
        current_don_vi = current_don_vi.don_vi_cha
      end
  
      ancestors
    end

  end
  

app/controllers/UploadsController.rb
class UploadsController < ApplicationController
  def new
    @duong_dan = nil

    if params[:don_vi].present?
      don_vi = DonVi.find_by_code(params[:don_vi])
      @don_vi = don_vi
      all_don_vi = don_vi.all_ancestors.pluck(:code)
      all_don_vi = all_don_vi.reverse 
      all_don_vi << don_vi.code
      @duong_dan = all_don_vi.join('/') if all_don_vi.present?
    end
  end

  def create
    s3 = Aws::S3::Resource.new(
      access_key_id: ENV['MIN_USER'],
      secret_access_key: ENV['MIN_PASSWORD'],
      endpoint: ENV['MIN_ENDPOINT'],
      force_path_style: true,
      region: "us-east-1"
    )
    bucket_name = params[:ten_bucket].present? ? params[:ten_bucket] : 'buck1'
    duong_dan = params[:duong_dan]
    file = params[:file]

    bucket = s3.bucket(bucket_name)

    file_path = file.original_filename
    file_path = File.join(duong_dan, file.original_filename) if duong_dan.present?

    # Kiểm tra xem bucket đã tồn tại chưa
    unless bucket.exists?
      bucket = s3.create_bucket(bucket: bucket_name)
    end

    obj = bucket.object(file_path)
    obj.upload_file(file.tempfile)

    p 'File uploaded successfully'
    redirect_to new_upload_path(don_vi: params[:don_vi].to_s), notice: 'File uploaded successfully'
  rescue StandardError => e
    flash[:alert] = "Error uploading file: #{e.message}"
    p "Error uploading file: #{e.message}"
    redirect_to new_upload_path(don_vi: params[:don_vi].to_s)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/don_vis_controller.rb
class DonVisController < ApplicationController
    def index
      # @don_vis = DonVi.all.order(:stt)
      @don_vis = DonVi.where(parent_code: nil)
    end

    def show
      @don_vi = DonVi.find(params[:id])
    end

    private

    def set_don_vi
      @don_vi = DonVi.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/don_vis/_don_vi.html.erb
<div>
  <%= '-' * level.to_i %>
  <strong><%= don_vi.ma_dinh_danh_dt %></strong>
  <span>. </span>

  <%= link_to new_upload_path(don_vi: don_vi.code) do %>
    <%= don_vi.ten %>
  <% end %>

  <% if don_vi.don_vi_con.present? %>
    <div>
      <% don_vi.don_vi_con.order(:code).each do |don_vi_con| %>
        <%= render partial: "don_vi", locals: { don_vi: don_vi_con, level: don_vi_con.cap } %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/don_vis/index.html.erb
<% cache ['don_vis', @don_vis.pluck('id')] do %>
<h1>Danh sách đơn vị hành chính</h1>

<div>
  <% @don_vis.each do |don_vi| %>
    <%= render partial: "don_vi", locals: { don_vi: don_vi, level: don_vi.cap } %>
  <% end %>
</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMinio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/uploads/new.html.erb
<h3>
<%= @don_vi&.code %>
-
<%= @don_vi&.ten %>
</h3>
<%= form_tag({ controller: 'uploads', action: 'create' }, multipart: true) do %>
  <input type="hidden" name="don_vi" value= <%= params[:don_vi].to_s %> >
  <div class="field">
    <label for="ten_bucket">Tên Bucket</label>
    <input type="text" id="ten_bucket" name="ten_bucket" placeholder="buc1" value='buc1'>
  </div>
  <br>

  <div class="field">
    <label for="duong_dan">Đường dẫn</label>
    <input type="text" id="duong_dan" name="duong_dan" placeholder="ha_noi/hoankiem" value=<%= @duong_dan %> >
  </div>
  <br>
  <%= file_field_tag 'file' %>
  <br>
  <br>
  <%= submit_tag 'Upload' %>
<% end %>


<br>
<br>
<%= link_to "Danh sach don vi", don_vis_path %>

<% if flash[:notice] %>
  <p class="alert alert-success"><%= flash[:notice] %></p>
<% elsif flash[:alert] %>
  <p class="alert alert-danger"><%= flash[:alert] %></p>
<% end %>